"""add video is_priority flag

Revision ID: 00f5942e3346
Revises: c4cbee008457
Create Date: 2026-07-23 18:27:40.298356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f5942e3346'
down_revision = 'c4cbee008457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_priority', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('is_priority')

    # ### end Alembic commands ###
