"""add regulation chunk and question tables

Revision ID: 6c86a07121ed
Revises: 605e0e4c38dd
Create Date: 2026-07-21 22:23:10.349746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c86a07121ed'
down_revision = '605e0e4c38dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulation_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('printed_page', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regulation_chunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regulation_chunk_printed_page'), ['printed_page'], unique=False)

    op.create_table('regulation_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('cited_pages', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regulation_question')
    with op.batch_alter_table('regulation_chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regulation_chunk_printed_page'))

    op.drop_table('regulation_chunk')
    # ### end Alembic commands ###
