"""add source to regulation chunks, rename cited_pages to citations

Revision ID: 77cb74f18da4
Revises: 6c86a07121ed
Create Date: 2026-07-21 22:48:49.869625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77cb74f18da4'
down_revision = '6c86a07121ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual nudge: existing rows predate the `source` column and are all from the AS3000
    # extraction, so backfill them with a server_default rather than leaving NOT NULL with
    # no default (which fails against a populated table). Re-running
    # scripts/extract_regulations.py afterward re-tags everything properly anyway.
    with op.batch_alter_table('regulation_chunk', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'source', sa.String(length=120), nullable=False,
                server_default='AS/NZS 3000:2018',
            )
        )
        batch_op.create_index(batch_op.f('ix_regulation_chunk_source'), ['source'], unique=False)

    with op.batch_alter_table('regulation_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('citations', sa.Text(), nullable=True))
        batch_op.drop_column('cited_pages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regulation_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cited_pages', sa.TEXT(), nullable=True))
        batch_op.drop_column('citations')

    with op.batch_alter_table('regulation_chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regulation_chunk_source'))
        batch_op.drop_column('source')

    # ### end Alembic commands ###
