"""add youtube_id and source_channel to video for linked external videos

Revision ID: 8ac2f3ce2fa1
Revises: 77cb74f18da4
Create Date: 2026-07-22 15:56:50.429382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac2f3ce2fa1'
down_revision = '77cb74f18da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('source_channel', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('source_channel')
        batch_op.drop_column('youtube_id')

    # ### end Alembic commands ###
