"""add last_login_at to user

Revision ID: af48d9ccc327
Revises: 8ac2f3ce2fa1
Create Date: 2026-07-22 18:35:46.192202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af48d9ccc327'
down_revision = '8ac2f3ce2fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')

    # ### end Alembic commands ###
